version: "3.9"
services:
  postgres:
    image: postgres:15.1
    env_file:
      - .env
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U finrep -d finrepbd" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s